### ISSUE TITLE
Unable to login after logout

### ISSUE THREAD

**Issue by knkrth** [HuJK/Cloud9-hub#6]
Hi, While logout & login with different user or the same user it keeps redirecting to the signin page.   We have to close that tab & open a new tab to login.

**Comment by HuJK** [comment]
https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication

So, my method is design a ```/401-logout.html```, 
which will tell you ```401 auth fail``` if you give *correct* password, 
and tell you ```200 OK, redirect to "/ide.html" by javascript``` if you give *wrong* password.

1. Google chrome received ```401 auth fail``` from ```/401-logout.html```, Then it will clear stored auth info, we logged out.
2. Then it goto ```/401-logout.html``` again due to last time authentication failure.
3. Then, google chrome received  ```200 OK, redirect to "/ide.html" by javascript```.
4. Then, we are in the "/ide.html". It received  ```401 auth fail``` again from ```/ide.html```. 
5. This time you have to type correct password to login.

The question is in the step 2, When google chrome goto ```/401-logout.html``` again, it popup password box again!

Actually in the ```401 auth fail``` page, I add a javascript to redirect user to ```/ide.html```, But Google chrome only run the code if user click "Cancel".
If user type wrong password, it will get ```200 OK``` and taken away from ```/401-logout.html``` by javascript.
The question is if user input correct password in ```/401-logout.html``` page, I can't take it away!

Do you have any idea to solve this problem?

**Comment by HuJK** [comment]
Okey, I came up with how to solve it. I use a file to represent this user is login or not.
When user login, I generate a file.
When user logout, I delete that file, and server tall browser ```401 auth fail``` to make browser clean the login info.
When second time the user visit logout.html(actually he want to login), Server will not do that, now user can login smoothly.
